<?php

class cls_adminpower {
    /* 后台管理权限 */

    public static $power = array(
        /* 用户管理 */
        'groupuser' => array('type' => 'group', 'title' => '用户管理', 'pid' => '',
//            'role' => 'sys,check,investment,online,leader',
            'access_name' => 'user',
            'page' => ''),
        'user_group' => array('type' => 'page', 'title' => '用户组', 'pid' => 'groupuser',
//            'role' => 'sys,check,leader',
            'access_name' => 'user/group',
            'page' => 'user/group.php'),
        'user_user' => array('type' => 'page', 'title' => '会员', 'id' => '', 'pid' => 'groupuser',
//            'role' => 'sys,check,investment,online,leader',
            'access_name' => 'user/user',
            'page' => 'user/user.php'),
         'user_admin' => array('type' => 'page', 'title' => '管理员', 'id' => '', 'pid' => 'groupuser',
//            'role' => 'sys,check,online,leader',
             'access_name' => 'user/admin',
            'page' => 'user/admin.php'),
         'access_mange' => array('type' => 'page', 'title' => '权限管理', 'id' => '', 'pid' => 'groupuser',
//            'role' => 'sys',
             'access_name' => 'user/access_mange',
            'page' => 'user/access_mange.php'),
        
        /* 商品管理 */
        'groupgoods' => array('type' => 'group', 'title' => '商品管理', 'pid' => '',
//            'role' => 'sys,check,investment,online,purchase,Finance,sale,leader',
             'access_name' => 'goods',
            'page' => ''),
        'goods_list' => array('type' => 'page', 'title' => '平台商品', 'id' => '', 'pid' => 'groupgoods',
//            'role' => 'sys,check,investment,online,Finance,leader',
             'access_name' => 'goods/list',
            'page' => 'goods/list.php'),
        'goods_store' => array('type' => 'page', 'title' => '商品仓库', 'id' => '', 'pid' => 'groupgoods',
//            'role' => 'sys,check,investment,purchase,Finance,leader',
            'access_name' => 'goods/store',
            'page' => 'goods/store.php'),
         'goods_counts' => array('type' => 'page', 'title' => '商品浏览统计', 'id' => '', 'pid' => 'groupgoods',
//            'role' => 'sys,check,investment,purchase,Finance,online,sale,leader',
             'access_name' => 'goods/counts',
            'page' => 'goods/counts.php'),
          'goods_comstorealarm' => array('type' => 'page', 'title' => '店铺库存警报', 'id' => '', 'pid' => 'groupgoods',
//            'role' => 'sys,check,investment,purchase,Finance,leader',
              'access_name' => 'goods/comstorealarm',
            'page' => 'goods/comstorealarm.php'),
          'goods_goodscount' => array('type' => 'page', 'title' => '商品统计', 'id' => '', 'pid' => 'groupgoods',
//            'role' => 'sys,check,investment,purchase,Finance,leader',
              'access_name' => 'goods/goodscount',
            'page' => 'goods/goodscount.php'),
        
         /* 财务管理 */
        'groupfinance' => array('type' => 'group', 'title' => '财务管理', 'pid' => '',
//            'role' => 'sys,check,Finance,online,leader',
            'access_name' => 'finance',
            'page' => ''),
        'finance_moneyin' => array('type' => 'page', 'title' => '用户入款', 'id' => '', 'pid' => 'groupfinance',
//            'role' => 'sys,check,Finance,online,leader',
            'access_name' => 'finance/moneyin',
            'page' => 'finance/moneyin.php'),
        'finance_account' => array('type' => 'page', 'title' => '资金统计', 'id' => '', 'pid' => 'groupfinance',
//            'role' => 'sys,check,Finance,online,leader',
            'access_name' => 'finance/account',
            'page' => 'finance/account.php'),
        'finance_accountday' => array('type' => 'page', 'title' => '日资金统计', 'id' => '', 'pid' => 'groupfinance',
//            'role' => 'sys,check,Finance,online,leader',
            'access_name' => 'finance/accountday',
            'page' => 'finance/accountday.php'),
        'finance_list' => array('type' => 'page', 'title' => '财务列表', 'id' => '', 'pid' => 'groupfinance',
//            'role' => 'sys,check,Finance,online,leader',
            'access_name' => 'finance/list',
            'page' => 'finance/list.php'),
         'finance_takelist' => array('type' => 'page', 'title' => '提现审核', 'id' => '', 'pid' => 'groupfinance',
//            'role' => 'sys,check,Finance,leader',
             'access_name' => 'finance/takelist',
            'page' => 'finance/takelist.php'),
         'finance_commoney' => array('type' => 'page', 'title' => '店铺财务', 'id' => '', 'pid' => 'groupfinance',
//            'role' => 'sys,check,Finance,leader',
             'access_name' => 'finance/commoney',
            'page' => 'finance/commoney.php'),        
        
         /* 赠款管理 */
        'groupvfinance' => array('type' => 'group', 'title' => '赠款管理', 'pid' => '',
//            'role' => 'sys,check,Finance,online,sale,leader',
            'access_name' => 'vfinance',
            'page' => ''),
        'vfinance_account' => array('type' => 'page', 'title' => '赠款统计', 'id' => '', 'pid' => 'groupvfinance',
//            'role' => 'sys,check,Finance,online,sale,leader',
            'access_name' => 'vfinance/account',
            'page' => 'vfinance/account.php'),
        'vfinance_list' => array('type' => 'page', 'title' => '赠款记录', 'id' => '', 'pid' => 'groupvfinance',
//            'role' => 'sys,check,Finance,online,sale,leader',
            'access_name' => 'vfinance/list',
            'page' => 'vfinance/list.php'),
        
        
         /* 业务管理 */
        'groupbusiness' => array('type' => 'group', 'title' => '业务管理', 'pid' => '',
//            'role' => 'sys,check,investment,online,sale,Finance,sale,leader,purchase',
            'access_name' => 'business',
            'page' => ''),
        'business_bizer' => array('type' => 'page', 'title' => '商家用户', 'id' => '', 'pid' => 'groupbusiness',
//            'role' => 'sys,check,investment,online,leader',
            'access_name' => 'business/bizer',
            'page' => 'business/bizer.php'),
        'business_company' => array('type' => 'page', 'title' => '店铺管理', 'id' => '', 'pid' => 'groupbusiness',
//            'role' => 'sys,check,sale,online,Finance,leader,purchase,investment',
            'access_name' => 'business/company',
            'page' => 'business/company.php'),
        'business_order' => array('type' => 'page', 'title' => '定单管理', 'id' => '', 'pid' => 'groupbusiness',
//            'role' => 'sys,check,online,Finance,leader',
            'access_name' => 'business/order',
            'page' => 'business/order.php'),
        'business_device' => array('type' => 'page', 'title' => '设备管理', 'id' => '', 'pid' => 'groupbusiness',
//            'role' => 'sys,check,online,leader',
            'access_name' => 'business/device',
            'page' => 'business/device.php'),
        'business_repair' => array('type' => 'page', 'title' => '设备维修', 'id' => '', 'pid' => 'groupbusiness',
//            'role' => 'sys,checke,online,leader',
            'access_name' => 'business/repair',
            'page' => 'business/repair.php'),
         'business_patrol' => array('type' => 'page', 'title' => '补换货记录', 'id' => '', 'pid' => 'groupbusiness',
//            'role' => 'sys,check,investment,online,sale,leader',
             'access_name' => 'business/patrol',
            'page' => 'business/patrol.php'),
        
         /* 在线调查 */
        'groupform' => array('type' => 'group', 'title' => '在线调查', 'pid' => '',
//            'role' => 'sys,check,investment,online,sale,leader',
            'access_name' => 'form',
            'page' => ''),
         'form_index' => array('type' => 'page', 'title' => '调查管理', 'id' => '', 'pid' => 'groupform',
//            'role' => 'sys,check,investment,online,sale,leader',
             'access_name' => 'form/index',
            'page' => 'form/index.php'),
        'form_joinus' => array('type' => 'page', 'title' => '招商加盟', 'id' => '', 'pid' => 'groupform',
//            'role' => 'sys,check,investment,online,sale,leader',
             'access_name' => 'form/joinus',
            'page' => 'form/joinus.php'),
        
         /* 数据管理 */
        'groupdata' => array('type' => 'group', 'title' => '数据管理', 'pid' => '',
//            'role' => 'sys',
            'access_name' => 'data',
            'page' => ''),
        'data_index' => array('type' => 'page', 'title' => '数据维护', 'id' => '', 'pid' => 'groupdata',
//            'role' => 'sys',
            'access_name' => 'data/index',
            'page' => 'data/index.php'),   
    );
    

}


